### PR TITLE
WIP: add clj

### PR DESCRIPTION
**Pull request by MitchellPavel**

### CODE REVIEW

**Comment by Torpus** [comment]
@MitchellPavel you want this merged in?

**Comment by MitchellPavel** [comment]
Nah I think Caleb already copy pasta'ed it in right?

**Comment by cujarrett** [comment]
> Nah I think Caleb already copy pasta'ed it in right?

@circa10a - $kr!pt k!ddy

**Comment by Torpus** [comment]
alt text

**Pull request closed without merging**
